### ISSUE TITLE
It doesn't work on win10

### ISSUE THREAD

**Issue by robozb** [HenryNguyen5/vsc-nvm#4]
A version argument is required but missing.

```
nvm use
A version argument is required but missing.
more .\.nvmrc
v19.1.0
```

**Comment by yisenliu** [comment]
same here

**Comment by zqy233** [comment]
> same here

try this
https://marketplace.visualstudio.com/items?itemName=nojsja.vscode-nvm
Or you can try what I wrote (not triggered by a terminal event, but by focusing a vscode window)
https://marketplace.visualstudio.com/items?itemName=zqy233.vscode-nvmrc
